mysql:
  host: 10.211.55.24
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: blog_server
  user: blog_server
  password: 7F3B4Hmjei2mZfDT
  log_level: dev
logger:
  level: info
  prefix: '[server]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release