mysql:
  host: 10.211.55.24
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: blog_server
  user: blog_server
  password: 7F3B4Hmjei2mZfDT
  log_level: dev
logger:
  level: info
  prefix: '[server]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
juhe:
  key: xxxx
jwt:
  secret: xxxx
  expires: 12
  issuer: xxxx
redis:
  ip: 10.211.55.24
  port: 6379
  password: "123456"
  pool_size: 999
email:
  host: smtp.qq.com
  port: 465
  send_email: xxxx@qq.com
  password: xxxx
  send_name: xxxx
  logo_email: xxxx
tianapi:
  key: xxxx
  dou_yin_hot: https://apis.tianapi.com/douyinhot/index?key=你的APIKEY
  network_hot: https://apis.tianapi.com/networkhot/index?key=你的APIKEY
  wei_bo_hot: https://apis.tianapi.com/weibohot/index?key=你的APIKEY
  bullet_in: https://apis.tianapi.com/bulletin/index?key=你的APIKEY
  zao_an: https://apis.tianapi.com/zaoan/index?key=你的APIKEY
  wan_an: https://apis.tianapi.com/wanan/index?key=你的APIKEY
  li_shi: https://apis.tianapi.com/lishi/index?key=你的APIKEY&date=0101
qi_niu:
  enable: false
  access_key: xxx
  secret_key: xxx
  bucket: xxx
  cdn: xxx
  zone: z0
  prefix: xxx
  size: 30
upload:
  size: 5
  path: uploads/file
site_info:
  create_at: "2023-06-13"
  bei_an: xxxx
  title: xxxx
  logo_light: xxxx
  logo_dark: xx
  favicon: xxx
  copyright_protocol: xxx
  copyright_info: xxx
  server_name: xx
  qq_image: xx
  gitee_url: https://gitee.com/xx/
  github_url: https://github.com/xx/
